version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: edu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql_db/data
    networks:
      - app-network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: reservation-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/edu
    ports:
      - "8080:8081"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network: